PRM.MVC/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PRM.API.Controllers;
using PRM.API.Controllers.Concretes;
using PRM.API.ViewModels.Album;

namespace PRM.MVC.Controllers
{
    [Authorize]
    public class AlbumController : BaseController
    {
        private ICommentApiController _commentApiController;
        private IAlbumApiController _albumApiController;
        private ILibraryApiController _libraryApiController;

        public AlbumController(IAlbumApiController albumApiController, ILibraryApiController libraryApiController, ICommentApiController commentApiController)
        {
            _albumApiController = albumApiController;
            _commentApiController = commentApiController;
            _libraryApiController = libraryApiController;
        }

        public ActionResult Index(string AlbumId)
        {
            Guid albumGuid = ParseRoutingGuid(AlbumId);
            if (albumGuid == Guid.Empty) return BaseItemNotFound();

            AlbumIndexViewModel viewModel = _albumApiController.GetAlbumIndexViewModel(albumGuid);

            return View(viewModel);
        }

        public ActionResult AlbumList()
        {
            var viewModel = _albumApiController.GetLibrariesWithAlbumsForUser(GetCurrentUserGuidId()).ToList();

            return View(viewModel);
        }

        public ActionResult Create()
        {
            Guid userId = GetCurrentUserGuidId();
            var viewModel = _albumApiController.GetCreateAlbumViewModel(userId);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(CreateAlbumViewModel viewModel)
        {
            var userId = GetCurrentUserId();

            viewModel.Album.CreatedByUser.Id = userId;
            viewModel.Album.TimespanType.Id = 1;

            var album = _albumApiController.CreateAlbum(viewModel);

            if (album.Id == Guid.Empty) return RedirectToAction("BaseError");

            return RedirectToAction("AlbumList");
        }

        public ActionResult Delete(string AlbumId)
        {
            Guid albumGuid = ParseRoutingGuid(AlbumId);
            var result = _albumApiController.DeleteAlbum(albumGuid);
            return RedirectToAction("AlbumList");
        }

    }
}

PRM.MVC/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PRM.API.Controllers;
using PRM.API.ViewModels.Comments;
using PRM.Data.Util;

namespace PRM.MVC.Controllers
{
    public class CommentController : BaseController
    {
        private ICommentApiController _commentApiController;

        public CommentController(ICommentApiController commentApiController)
        {
            _commentApiController = commentApiController;
        }

        //public ActionResult CreateComment(string ContentId, string ContentTypeId)
        //{

        //}

        public ActionResult CreateComment(string ContentId, string ContentTypeId)
        {
            var userId = GetCurrentUserGuidId();
            var contentId = ParseRoutingGuid(ContentId);
            var contentTypeId = ParseRoutingInt(ContentTypeId);

            var viewModel = _commentApiController.GetCreateCommentViewModel(userId, contentId, contentTypeId);

            return PartialView("_CreateComment", viewModel);
        }

        [HttpPost]
        public ActionResult CreateComment(CreateCommentViewModel viewModel)
        {
            var userId = GetCurrentUserGuidId();
            viewModel.Comment.User.Id = userId.ToString();
            var comment = _commentApiController.CreateComment(viewModel);

            switch (comment.ContentType.Id)
            {
                case (int)ContentTypesEnum.ALBUM: return RedirectToAction("Index", "Album", new { AlbumId = comment.ContentId.ToString() });
            }

            return RedirectToAction("Index","Home");
        }
    }
}

PRM.MVC/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PRM.API.Controllers;
using PRM.API.Controllers.Concretes;
using PRM.API.ViewModels.Album;
using Newtonsoft.Json.Linq;
using PRM.Data.Models;
using PRM.Data.Util;

namespace PRM.MVC.Controllers
{
    public class ImageController : BaseController
    {
        private IAlbumApiController _albumApiController;
        private IImageApiController _imageApiController;
        private ILibraryApiController _libraryApiController;

        public ImageController(IAlbumApiController albumApiController,
                                IImageApiController imageApiController,
                                ILibraryApiController libraryApiController)
        {
            _albumApiController = albumApiController;
            _imageApiController = imageApiController;
            _libraryApiController = libraryApiController;
        }

        public ActionResult AddImage(string AlbumId)
        {
            Guid albumId = ParseRoutingGuid(AlbumId);
            if (albumId == Guid.Empty) return BaseItemNotFound();

            var viewModel = _imageApiController.GetAddImageViewModel(albumId);

            return PartialView("_AddImage", viewModel);
        }

       
        [HttpPost]
        [ActionName("MultiImageUpload")]
        public void MultiImageUpload(AddImageViewModel viewModel)
        {
            Guid userId = GetCurrentUserGuidId();
            Guid albumId = viewModel.AlbumId;
            viewModel.Image = new Image();
            viewModel.Image.Description = "Desc";
            viewModel.Image.UploadedByUser = new User() { Id = userId.ToString() };
            viewModel.Image.Id = Guid.NewGuid();
            var result = _imageApiController.AddImageToAlbum(viewModel);
        }

        [HttpPost]
        public ActionResult AddImage(AddImageViewModel viewModel)
        {
            Guid userId = GetCurrentUserGuidId();
            Guid albumId = viewModel.AlbumId;
            viewModel.Image.UploadedByUser = new User() { Id = userId.ToString() };
            var result = _imageApiController.AddImageToAlbum(viewModel);

            return RedirectToAction("Index", "Album", new { AlbumId = albumId.ToString() });
        }

        public ActionResult RotateImage(string AlbumId, string ImageId, string RotationAngle)
        {
            Guid userId = GetCurrentUserGuidId();
            Guid albumId = ParseRoutingGuid(AlbumId);
            Guid imageId = ParseRoutingGuid(ImageId);
            int rotationAngle = ParseRoutingInt(RotationAngle);

            var result = _imageApiController.RotateImage(albumId, imageId, rotationAngle);

            return RedirectToAction("Index", "Album", new { AlbumId = AlbumId });
        }

        public ActionResult DeleteImageFromAlbum(Guid imageId, Guid albumId)
        {
            Guid userId = GetCurrentUserGuidId();

            _imageApiController.DeleteImageFromAlbum(userId, imageId, albumId);

            return RedirectToAction("Index", "Album", new { AlbumId = albumId });
        }

        public ActionResult AjaxAddImage(string AlbumId)
        {
            Guid albumId = ParseRoutingGuid(AlbumId);
            if (albumId == Guid.Empty) return BaseItemNotFound();

            var viewModel = _imageApiController.GetAddImageViewModel(albumId);

            return PartialView("_AjaxAddImage", viewModel);
        }

        [HttpPost]
        public ActionResult AjaxAddImage(AddImageViewModel viewModel)
        {
            //Call to api controller here, similar to AddImage()

            Guid userId = GetCurrentUserGuidId();
            Guid albumId = viewModel.AlbumId;
            viewModel.Image = new PRM.Data.Models.Image()
            {
                ContentyType = new ContentType() { Id = (int)ContentTypesEnum.IMAGE },
                UploadedByUser = new User() { Id = userId.ToString() },
            };


            var result = _imageApiController.AddImageToAlbum(viewModel);

            try
            {
                return PartialView("~/Views/Image/_Image.cshtml", viewModel.Image/*new PRM.Data.Data.Image()*/);
            }
            catch (Exception e)
            {
                dynamic json = new JObject();
                    json.Status = "Error";
                    json.Error = e;
                    json.ImageId = viewModel.Image.Id;
                
                return json;
            }
        }


    }
}

PRM.MVC/Views/Album/AlbumList.cshtml
@model List<PRM.Data.Models.Library>
@{
    ViewBag.Title = "AlbumList";
}

<h3>All Albums</h3>
@Html.ActionLink("Create New Album", "Create", "Album", new { }, new { @class = "label label-primary" })

@foreach(var library in Model)
{
    <div>
        <h3>Library • @library.Title</h3>
        <ul>
            @foreach (var album in library.Albums)
            {
                <li>
                    @Html.ActionLink("Delete", "Delete", "Album", new { AlbumId = album.Id.ToString("N") }, new { @Class="label label-danger" })
                    @Html.ActionLink(album.Title, "Index", "Album", new { AlbumId = album.Id.ToString("N") }, new { })
                </li>
            }
        </ul>
    </div>
}

PRM.MVC/Views/Album/Create.cshtml
@model PRM.API.ViewModels.Album.CreateAlbumViewModel
@{
    ViewBag.Title = "Create";
}
<script type="text/javascript">
    $(document).ready(function () {
        $("#timespan_details").hide();
        $(":radio:eq(0)").click(function(){
            $("#timespan_details").fadeIn();
        });

        $(":radio:eq(1)").click(function(){
            $("#timespan_details").fadeOut();
        });
    });


</script>
<h2>Create</h2>
@*
    TODO: Mason try this method of creating dropdowns
    Model.AllStores.Select(x => new SelectListItem { Value = x.Name, Text = x.Name, Selected = x.Name == Model.StoreNumber })
*@
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    @Html.HiddenFor(m=>m.Album.CreatedByUser.Id)

    <div class="form-horizontal">
        <h4>Album</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Album.Library.Id, "Library", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.Album.Library.Id, Model.LibraryDropdown)
                @Html.ValidationMessageFor(model => model.Album.Library.Id, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Album.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Album.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Album.Title, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Album.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Album.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Album.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Album.HasTimespan, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.Album.HasTimespan, true, new { htmlAttributes = new { @class = "form-control" } }) True
                @Html.RadioButtonFor(model => model.Album.HasTimespan, false, new { htmlAttributes = new { @class = "form-control" } }) False
                @Html.ValidationMessageFor(model => model.Album.HasTimespan, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="timespan_details">
            <div class="form-group">
                @Html.LabelFor(model => model.Album.TimespanType, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Album.TimespanType, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Album.TimespanType, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Album.TimespanStart, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Album.TimespanStart, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Album.TimespanStart, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Album.TimespanEnd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Album.TimespanEnd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Album.TimespanEnd, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
  
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PRM.MVC/Views/Album/Index.cshtml
@model PRM.API.ViewModels.Album.AlbumIndexViewModel


@{ ViewBag.Title = "Album | " + Model.album.Title; }

<h2>@Model.album.Title</h2>

<p>@Model.album.Description</p>

    <div class="row">
        <div class="col-md-12">
            @Html.Action("AjaxAddImage", "Image", new { AlbumId = Model.album.Id })
            @*@Html.Action("AddImage", "Image", new { AlbumId = Model.album.Id })*@
        </div>
    </div>

<div id="js-image-container">
    @foreach (var item in Model.images)
    {
        @Html.Partial("~/Views/Image/_Image.cshtml",item)
    }
</div>


<div style="clear:both;"></div>

<br />
<hr />
@Html.Action("CreateComment", "Comment", new { ContentId = Model.album.Id, ContentTypeId = ((int)PRM.Data.Util.ContentTypesEnum.ALBUM).ToString() })
<br />
<hr />
<b>Comments</b>
<br />

@foreach (var item in Model.comments)
{
    <div class="comment">
        <p>@item.Text</p>
    </div>
}



<style>
     .comment {
         border: 1px solid black;
         margin: 0 0 10px 0;
     }
    .imageContainer {
        float:left;
        margin: 5px;
        padding: 5px;
    }
    .imageContainer:hover {
        border: 3px solid #428bca;
        padding: 2px;
    }
    .imageContainer img {
        max-height: 300px;
        max-height: 300px;
    } 

</style>