PRM.MVC/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PRM.API.Controllers;
using PRM.API.Controllers.Concretes;
using PRM.API.ViewModels.Album;

namespace PRM.MVC.Controllers
{
    [Authorize]
    public class AlbumController : BaseController
    {
        private ICommentApiController _commentApiController;
        private IAlbumApiController _albumApiController;
        private ILibraryApiController _libraryApiController;

        public AlbumController(IAlbumApiController albumApiController, ILibraryApiController libraryApiController, ICommentApiController commentApiController)
        {
            _albumApiController = albumApiController;
            _commentApiController = commentApiController;
            _libraryApiController = libraryApiController;
        }

        public ActionResult Index(string AlbumId)
        {
            Guid albumGuid = ParseRoutingGuid(AlbumId);
            if (albumGuid == Guid.Empty) return BaseItemNotFound();

            AlbumIndexViewModel viewModel = _albumApiController.GetAlbumIndexViewModel(albumGuid);

            return View(viewModel);
        }

        public ActionResult AlbumList()
        {
            var viewModel = _albumApiController.GetLibrariesWithAlbumsForUser(GetCurrentUserGuidId()).ToList();

            return View(viewModel);
        }

        public ActionResult Create()
        {
            Guid userId = GetCurrentUserGuidId();
            var viewModel = _albumApiController.GetCreateAlbumViewModel(userId);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult Create(CreateAlbumViewModel viewModel)
        {
            var userId = GetCurrentUserId();

            viewModel.Album.CreatedByUser.Id = userId;
            viewModel.Album.TimespanType.Id = 1;

            var album = _albumApiController.CreateAlbum(viewModel);

            if (album.Id == Guid.Empty) return RedirectToAction("BaseError");

            return RedirectToAction("AlbumList");
        }

        public ActionResult Delete(string AlbumId)
        {
            Guid albumGuid = ParseRoutingGuid(AlbumId);
            var result = _albumApiController.DeleteAlbum(albumGuid);
            return RedirectToAction("AlbumList");
        }

    }
}

PRM.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PRM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Albums", "AlbumList", "Album")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>